/**
 * Relaciones FK del esquema (generado desde db/migrations/0001_init.sql).
 * Usado por el compilador para inferir los joins de los embedded selects.
 * Regenerar si cambian las FKs: ver docs/portable-data-layer.md.
 */
export interface FkRef {
  table: string;
  column: string;
  refTable: string;
  refColumn: string;
}

export const FOREIGN_KEYS: FkRef[] = [
  {
    table: 'account_invitations',
    column: 'accepted_by_user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'account_invitations',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'account_invitations',
    column: 'created_by_user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'accounts',
    column: 'owner_user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'ai_configs',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'ai_configs',
    column: 'created_by',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'ai_knowledge_chunks',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'ai_knowledge_chunks',
    column: 'document_id',
    refTable: 'ai_knowledge_documents',
    refColumn: 'id',
  },
  {
    table: 'ai_knowledge_documents',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'ai_knowledge_documents',
    column: 'created_by',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'api_keys',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'api_keys',
    column: 'created_by',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'automation_logs',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'automation_logs',
    column: 'automation_id',
    refTable: 'automations',
    refColumn: 'id',
  },
  {
    table: 'automation_logs',
    column: 'contact_id',
    refTable: 'contacts',
    refColumn: 'id',
  },
  {
    table: 'automation_logs',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'automation_pending_executions',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'automation_pending_executions',
    column: 'automation_id',
    refTable: 'automations',
    refColumn: 'id',
  },
  {
    table: 'automation_pending_executions',
    column: 'contact_id',
    refTable: 'contacts',
    refColumn: 'id',
  },
  {
    table: 'automation_pending_executions',
    column: 'log_id',
    refTable: 'automation_logs',
    refColumn: 'id',
  },
  {
    table: 'automation_pending_executions',
    column: 'parent_step_id',
    refTable: 'automation_steps',
    refColumn: 'id',
  },
  {
    table: 'automation_pending_executions',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'automation_steps',
    column: 'automation_id',
    refTable: 'automations',
    refColumn: 'id',
  },
  {
    table: 'automation_steps',
    column: 'parent_step_id',
    refTable: 'automation_steps',
    refColumn: 'id',
  },
  {
    table: 'automations',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'automations',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'broadcast_recipients',
    column: 'broadcast_id',
    refTable: 'broadcasts',
    refColumn: 'id',
  },
  {
    table: 'broadcast_recipients',
    column: 'contact_id',
    refTable: 'contacts',
    refColumn: 'id',
  },
  {
    table: 'broadcasts',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'broadcasts',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'contact_custom_values',
    column: 'contact_id',
    refTable: 'contacts',
    refColumn: 'id',
  },
  {
    table: 'contact_custom_values',
    column: 'custom_field_id',
    refTable: 'custom_fields',
    refColumn: 'id',
  },
  {
    table: 'contact_notes',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'contact_notes',
    column: 'contact_id',
    refTable: 'contacts',
    refColumn: 'id',
  },
  {
    table: 'contact_notes',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'contact_tags',
    column: 'contact_id',
    refTable: 'contacts',
    refColumn: 'id',
  },
  {
    table: 'contact_tags',
    column: 'tag_id',
    refTable: 'tags',
    refColumn: 'id',
  },
  {
    table: 'contacts',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  { table: 'contacts', column: 'user_id', refTable: 'users', refColumn: 'id' },
  {
    table: 'conversations',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'conversations',
    column: 'contact_id',
    refTable: 'contacts',
    refColumn: 'id',
  },
  {
    table: 'conversations',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'custom_fields',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'custom_fields',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'deals',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'deals',
    column: 'assigned_to',
    refTable: 'profiles',
    refColumn: 'id',
  },
  {
    table: 'deals',
    column: 'contact_id',
    refTable: 'contacts',
    refColumn: 'id',
  },
  {
    table: 'deals',
    column: 'conversation_id',
    refTable: 'conversations',
    refColumn: 'id',
  },
  {
    table: 'deals',
    column: 'pipeline_id',
    refTable: 'pipelines',
    refColumn: 'id',
  },
  {
    table: 'deals',
    column: 'stage_id',
    refTable: 'pipeline_stages',
    refColumn: 'id',
  },
  { table: 'deals', column: 'user_id', refTable: 'users', refColumn: 'id' },
  {
    table: 'flow_nodes',
    column: 'flow_id',
    refTable: 'flows',
    refColumn: 'id',
  },
  {
    table: 'flow_run_events',
    column: 'flow_run_id',
    refTable: 'flow_runs',
    refColumn: 'id',
  },
  {
    table: 'flow_runs',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'flow_runs',
    column: 'contact_id',
    refTable: 'contacts',
    refColumn: 'id',
  },
  {
    table: 'flow_runs',
    column: 'conversation_id',
    refTable: 'conversations',
    refColumn: 'id',
  },
  { table: 'flow_runs', column: 'flow_id', refTable: 'flows', refColumn: 'id' },
  {
    table: 'flow_runs',
    column: 'last_prompt_message_id',
    refTable: 'messages',
    refColumn: 'id',
  },
  { table: 'flow_runs', column: 'user_id', refTable: 'users', refColumn: 'id' },
  {
    table: 'flows',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  { table: 'flows', column: 'user_id', refTable: 'users', refColumn: 'id' },
  {
    table: 'member_presence',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'member_presence',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'message_reactions',
    column: 'conversation_id',
    refTable: 'conversations',
    refColumn: 'id',
  },
  {
    table: 'message_reactions',
    column: 'message_id',
    refTable: 'messages',
    refColumn: 'id',
  },
  {
    table: 'message_templates',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'message_templates',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'messages',
    column: 'conversation_id',
    refTable: 'conversations',
    refColumn: 'id',
  },
  {
    table: 'messages',
    column: 'reply_to_message_id',
    refTable: 'messages',
    refColumn: 'id',
  },
  {
    table: 'notifications',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'notifications',
    column: 'actor_user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'notifications',
    column: 'contact_id',
    refTable: 'contacts',
    refColumn: 'id',
  },
  {
    table: 'notifications',
    column: 'conversation_id',
    refTable: 'conversations',
    refColumn: 'id',
  },
  {
    table: 'notifications',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'oidc_identities',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'password_reset_tokens',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'pipeline_stages',
    column: 'pipeline_id',
    refTable: 'pipelines',
    refColumn: 'id',
  },
  {
    table: 'pipelines',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  { table: 'pipelines', column: 'user_id', refTable: 'users', refColumn: 'id' },
  {
    table: 'profiles',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  { table: 'profiles', column: 'user_id', refTable: 'users', refColumn: 'id' },
  { table: 'sessions', column: 'user_id', refTable: 'users', refColumn: 'id' },
  {
    table: 'tags',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  { table: 'tags', column: 'user_id', refTable: 'users', refColumn: 'id' },
  {
    table: 'webhook_endpoints',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'webhook_endpoints',
    column: 'created_by',
    refTable: 'users',
    refColumn: 'id',
  },
  {
    table: 'whatsapp_config',
    column: 'account_id',
    refTable: 'accounts',
    refColumn: 'id',
  },
  {
    table: 'whatsapp_config',
    column: 'user_id',
    refTable: 'users',
    refColumn: 'id',
  },
];
